import { registry } from './tools/toolRegistry';
import { getAssetsTool, allocateAssetTool } from './tools/assetTools';
import { bookResourceTool, getBookingsTool } from './tools/bookingTools';
import { raiseMaintenanceTool, getMaintenanceRequestsTool } from './tools/maintainanceTool';
import { getAssetUtilizationTool, getOverdueAllocationsTool } from './tools/reportTools';
import { getUsersTool, getDepartmentsTool } from './tools/userTools';
import { Planner } from './planner/planner';
import { validatePlan } from './planner/validator';
import { Executor } from './executor/executer';
import { OllamaProvider } from './provider/ollama';
import { AgentResponse, Plan } from './types';

import { ConversationMemory } from './memory/conversationMemory';

// Register all tools
registry.registerTool(getAssetsTool);
registry.registerTool(allocateAssetTool);
registry.registerTool(bookResourceTool);
registry.registerTool(getBookingsTool);
registry.registerTool(raiseMaintenanceTool);
registry.registerTool(getMaintenanceRequestsTool);
registry.registerTool(getAssetUtilizationTool);
registry.registerTool(getOverdueAllocationsTool);
registry.registerTool(getUsersTool);
registry.registerTool(getDepartmentsTool);

export class AssetFlowAgent {
  private planner: Planner;
  private executor: Executor;
  private provider: OllamaProvider;
  private memory: ConversationMemory;

  constructor() {
    this.planner = new Planner();
    this.executor = new Executor();
    this.provider = new OllamaProvider();
    this.memory = new ConversationMemory();
  }

  async processQuery(query: string): Promise<AgentResponse> {
    try {
      this.memory.addMessage({ role: 'user', content: query });
      
      const availableTools = registry.getAllTools();
      const history = this.memory.getFormattedHistory();
      
      // Step 1: Planning
      const plan: Plan = await this.planner.createPlan(query, availableTools, history);

      // Step 2: Validation
      const isValid = validatePlan(plan, availableTools);
      if (!isValid) {
        return { success: false, message: 'Invalid plan generated by AI.' };
      }

      // Step 3: Execution
      const results = await this.executor.executePlan(plan, availableTools);

      // Step 4: Final Output Generation
      const synthesisPrompt = `You are AssetFlow AI. The user asked: "${query}". 
The plan's intended output was: "${plan.Output}".
The tools executed with the following results: ${JSON.stringify(results)}.
Conversation History:
${history}
Please provide a concise, final response to the user based on these results.`;

      const finalMessage = await this.provider.generate(synthesisPrompt);
      this.memory.addMessage({ role: 'assistant', content: finalMessage });

      return {
        success: true,
        message: finalMessage,
        data: results
      };
    } catch (error: any) {
      console.error('Agent error:', error);
      return { success: false, message: error.message || 'An error occurred during processing.' };
    }
  }
}
